module.exports = [
  {
    name: 'Going Home...',
    type: 'Card',
    condition: 'Very Good',
    content: 'Program',
    publisher: 'A. Barrett Funeral Services, Inc.',
  },
  {
    name: 'Where are you going?',
    type: 'Pamphlet',
    condition: 'Good',
    content: 'Self-Help',
    publisher: 'Hope Tract Ministry',
  },
  {
    name: 'Your Ticket to Heaven',
    type: 'Leaflet',
    condition: 'Mint',
    content: 'Informational',
    publisher: 'Good News Tracts',
  },
  {
    name: 'The Greatest Journey',
    type: 'Pamphlet',
    condition: 'Good',
    content: 'Infographic',
    publisher: 'Moments With The Book',
  },
  {
    name: 'Are You Thirsty?',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Self-Help',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Are You A Good Person?',
    type: 'Card',
    condition: 'Mint',
    content: 'Self-Help',
    publisher: 'Bezeugen',
  },
  {
    name: 'Are YOU good Enough?',
    type: 'Leaflet',
    condition: 'Okay',
    content: 'History',
    publisher: 'Israel Restoration Ministries',
  },
  {
    name: 'Are You Faster Than Lightning?',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Advice',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Storms In The Night!',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Story',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Walking On Thin Ice!',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Story',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'On The Run!',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Self-Help',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Out Of The Blue',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Story',
    publisher: 'American Tract Society',
  },
  {
    name: 'Which Way Are You Going?',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Self-Help',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Do Not OPEN This!',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Advice',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'The Trinity',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Informational',
    publisher: 'Heritage Baptist Church',
  },
  {
    name: 'Drums In Church?',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Informational',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Satan\'s Web - Rock Music',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Informational',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Body Piercing - How Much Is Too Much?',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Educational',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Final Exam - Ready for It?',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Educational',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'I.Q. TEST',
    type: 'Card',
    condition: 'Good',
    content: 'Educational',
    publisher: 'Living Waters',
  },
  {
    name: 'On a scale of 0 to 10, how certain are you that you will go to Heaven?',
    type: 'Card',
    condition: 'Very Good',
    content: 'Informational',
    publisher: 'Bezeugen',
  },
  {
    name: 'A Load Too Great For The Engineer\'s Scale!',
    type: 'Leaflet',
    condition: 'Very',
    content: 'Story',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: '4 Things GOD wants you to know',
    type: 'Pamphlet',
    condition: 'Very Good',
    content: 'Informational',
    publisher: 'Good News Tracts',
  },
  {
    name: 'Hey, I\'m doing the best I can!',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Advice',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'did you get 1 of these?',
    type: 'Card',
    condition: 'Very Good',
    content: 'Informational',
    publisher: 'Bezeugen',
  },
  {
    name: 'Liberty Bible Course',
    type: 'Booklet',
    condition: 'Very Good',
    content: 'Educational',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'What Does The FUTURE Hold For You?',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Professional Development',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Would Jesus Buy It?',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Industry Analysis',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Who Is He?',
    type: 'Tract',
    condition: 'Very Good',
    content: 'Comic',
    publisher: 'Chick Tracts',
  },
  {
    name: 'JESUS IS KING',
    type: 'Card',
    condition: 'Mint',
    content: 'Informational',
    publisher: 'Bezeugen',
  },
  {
    name: 'It\'s About Tim!',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Educational',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Time Alone With God',
    type: 'Tract',
    condition: 'Mint',
    content: 'Informational',
    publisher: 'Billy Graham Evangelistic Association',
  },
  {
    name: 'If you had THREE MINUTES TO LIVE...',
    type: 'Card',
    condition: 'Very Good',
    content: 'Informational',
    publisher: 'Bezeugen',
  },
  {
    name: 'What To Tell A Person Who Has Five Minutes To Live!',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Educational',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'HOT LINE TO HELL',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'History',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'Get Out of Hell Free',
    type: 'Card',
    condition: 'Very Good',
    content: 'Advice',
    publisher: 'Bezeugen',
  },
  {
    name: 'Free Indeed',
    type: 'Card',
    condition: 'Very Good',
    content: 'Informational',
    publisher: 'Bezeugen',
  },
  {
    name: 'What happens after #YOLO?',
    type: 'Card',
    condition: 'Very Good',
    content: 'Advice',
    publisher: 'Bezeugen',
  },
  {
    name: 'Good News for All Ages!',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Comic',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'You\'re Special',
    type: 'Pamphlet',
    condition: 'Very Good',
    content: 'Informational',
    publisher: 'Good News Tracts',
  },
  {
    name: 'Someone Cares About You',
    type: 'Leaflet',
    condition: 'Good',
    content: 'Informational',
    publisher: 'Signs of the Times',
  },
  {
    name: 'Jesus Loves You!',
    type: 'Card',
    condition: 'Okay',
    content: 'Informational',
    publisher: 'Moments With The Book',
  },
  {
    name: 'Acceptance',
    type: 'Booklet',
    condition: 'Very Good',
    content: 'Self-Help',
    publisher: 'Abbey Press',
  },
  {
    name: 'What Must I Do To Be Saved?',
    type: 'Pamphlet',
    condition: 'Very Good',
    content: 'Educational',
    publisher: 'American Tract Society',
  },
  {
    name: 'The Plan Of Salvation',
    type: 'Booklet',
    condition: 'Very Good',
    content: 'Informational',
    publisher: 'The Church of Jesus Christ of Latter-Day Saints',
  },
  {
    name: 'I am NOT interested!',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Advice',
    publisher: 'Liberty Gospel Tracts',
  },
  {
    name: 'I\'m Jewish and I am not interested!',
    type: 'Leaflet',
    condition: 'Mint',
    content: 'Advice',
    publisher: 'End-Time Fellowship',
  },
  {
    name: 'Is He Good For The Jews?',
    type: 'Leaflet',
    condition: 'Mint',
    content: 'Informational',
    publisher: 'Messianic Literature Outreach',
  },
  {
    name: 'My mother was right!',
    type: 'Leaflet',
    condition: 'Very Good',
    content: 'Story',
    publisher: 'Messianic Literature Outreach',
  },
  {
    name: 'Jesus in Islam',
    type: 'Leaflet',
    condition: 'Good',
    content: 'Educational',
    publisher: 'Why Islam?',
  },
].map((d, i) => ({
  name: d.name,
  attributes: [
    {
      trait_type: "Type",
      value: d.type
    },
    {
      trait_type: "Condition",
      value: d.condition
    },
    {
      trait_type: "Content",
      value: d.content
    },
    {
      trait_type: "Publisher",
      value: d.publisher
    },
    {
      trait_type: "Year",
      value: '2023'
    }
  ],
  token_id: String(i + 125),
  external_url: `https://steviep.xyz/jesus/pamphlets/${i+125}`,
  description: `Photograph by Steve Pikelny (${2023}) | Published by ${d.publisher} | Content: ${d.content} | Condition: ${d.condition} | Type: ${d.type}`
}))